'use strict'

module.exports = {
  theme: {
    extend: {
      colors: {
        'bg-base': 'var(--bg-base)',
        'bg-subtle': 'var(--bg-subtle)',
        'surface-card': 'var(--surface-card)',
        'surface-raised': 'var(--surface-raised)',
        'surface-sunken': 'var(--surface-sunken)',
        'text-strong': 'var(--text-strong)',
        'text-body': 'var(--text-body)',
        'text-muted': 'var(--text-muted)',
        'text-on-brand': 'var(--text-on-brand)',
        'text-on-accent': 'var(--text-on-accent)',
        'border-subtle': 'var(--border-subtle)',
        'border-strong': 'var(--border-strong)',
        brand: 'var(--brand)',
        'brand-strong': 'var(--brand-strong)',
        accent: 'var(--accent)',
        'accent-strong': 'var(--accent-strong)',
        // Semantic state colors
        'danger':        'var(--kipo-danger)',
        'danger-soft':   'var(--kipo-danger-bg)',
        'success':       'var(--kipo-success)',
        'success-soft':  'var(--kipo-success-bg)',
        'warning':       'var(--kipo-warning)',
        'warning-soft':  'var(--kipo-warning-bg)',
        'info':          'var(--kipo-info)',
        'info-soft':     'var(--kipo-info-bg)',
        // Surface extras
        'surface-muted': 'var(--bg-subtle)',
        'surface-brand-soft': 'var(--surface-brand-soft)',
        'banner-warning-bg': 'var(--banner-warning-bg)',
        'banner-warning-border': 'var(--banner-warning-border)',
        'banner-warning-icon': 'var(--banner-warning-icon)',
        'banner-warning-text': 'var(--banner-warning-text)',
        'banner-warning-link': 'var(--banner-warning-link)',
        'kipo-slate-900': 'var(--kipo-slate-900)',
        // Raw palette (kept for escape-hatch use)
        kipo: {
          red: '#e00b26',
          'red-dark': '#bc0921',
          lime: '#C6F542',
          success: '#16A34A',
          warning: '#CA8A04',
          danger: '#bc0921',
          info: '#7C3AED',
        },
      },
      fontFamily: {
        display: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        body: ['"Inter"', 'system-ui', 'sans-serif'],
        mono: ['"Geist Mono"', 'ui-monospace', '"SF Mono"', 'monospace'],
        'plus-jakarta': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        urbanist: ['"Urbanist"', 'system-ui', 'sans-serif'],
        lato: ['"Lato"', 'system-ui', 'sans-serif'],
        inter: ['"Inter"', 'system-ui', 'sans-serif'],
        'geist-mono': ['"Geist Mono"', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        'kipo-xs': '6px',
        'kipo-sm': '8px',
        'kipo': '12px',
        'kipo-lg': '16px',
        'kipo-xl': '24px',
        'kipo-pill': '999px',
      },
      boxShadow: {
        'kipo-xs': '0 1px 2px rgba(3, 38, 65, 0.06)',
        'kipo-sm': '0 2px 8px rgba(3, 38, 65, 0.08)',
        'kipo-md': '0 6px 20px rgba(3, 38, 65, 0.10)',
        'kipo-lg': '0 16px 40px rgba(3, 38, 65, 0.14)',
        'kipo-brand': '0 10px 30px rgba(224, 11, 38, 0.28)',
        'kipo-accent': '0 8px 24px rgba(169, 217, 43, 0.35)',
      },
    },
  },
  plugins: [],
};
