CARTA_PORTE_CATALOGS: dict[str, str] = {
    "motivo_traslado": "sat_motivo_traslado",
    "medio_transporte": "sat_medio_transporte",
    "tipo_estacion": "sat_tipo_estacion",
    "permiso_sct": "sat_permiso_sct",
    "sector_cofepris": "sat_sector_cofepris",
    "forma_farmaceutica": "sat_forma_farmaceutica",
    "condiciones_especiales": "sat_condiciones_especiales",
    "tipo_materia": "sat_tipo_materia",
    "tipo_documento_aduanero": "sat_tipo_documento_aduanero",
    "parte_transporte": "sat_parte_transporte",
    "figura_transporte": "sat_figura_transporte",
    "registro_istmo": "sat_registro_istmo",
    "clave_tipo_carga": "sat_clave_tipo_carga",
    "configuracion_maritima": "sat_configuracion_maritima",
    "trafico_ferroviario": "sat_trafico_ferroviario",
    "tipo_contenedor": "sat_tipo_contenedor",
    "tipo_contenedor_maritimo": "sat_tipo_contenedor_maritimo",
    "tipo_carro_ferroviario": "sat_tipo_carro_ferroviario",
    "tipo_servicio_ferroviario": "sat_tipo_servicio_ferroviario",
    "permiso_hidrocarburos": "sat_permiso_hidrocarburos",
    "clave_hyp": "sat_clave_hyp",
    "subproducto_hyp": "sat_subproducto_hyp",
}

COMERCIO_EXTERIOR_CATALOGS: dict[str, str] = {
    "regimen_aduanero": "sat_regimen_aduanero",
    "incoterm": "sat_incoterm",
    "unidad_aduana": "sat_unidad_aduana",
}

CFDI_CATALOGS: dict[str, str] = {
    "forma_pago": "sat_forma_pago",
    "metodo_pago": "sat_metodo_pago",
    "regimen_fiscal": "sat_regimen_fiscal",
    "uso_cfdi": "sat_uso_cfdi",
    "relacion_facturas": "sat_relacion_facturas",
    "mes": "sat_mes",
    "objeto_imp": "sat_objeto_imp",
    "iva_tasa": "sat_iva_tasa",
    "tipo_contrato": "sat_tipo_contrato",
    "tipo_jornada": "sat_tipo_jornada",
    "tipo_regimen_nomina": "sat_tipo_regimen_nomina",
    "riesgo_puesto": "sat_riesgo_puesto",
    "periodicidad_pago": "sat_periodicidad_pago",
    "tipo_percepcion": "sat_tipo_percepcion",
    "tipo_horas": "sat_tipo_horas",
    "tipo_deduccion": "sat_tipo_deduccion",
    "tipo_otro_pago": "sat_tipo_otro_pago",
    "tipo_incapacidad": "sat_tipo_incapacidad",
    "clave_retencion": "sat_clave_retencion",
    "validez_obligaciones": "sat_validez_obligaciones",
    "situacion_contribuyente": "sat_situacion_contribuyente",
}
